### ISSUE TITLE
Background-image support

### ISSUE THREAD

**Issue by tadaskarpavicius** [scottjehl/picturefill#235]
Hi, first of all, awesome plugin! I love it and use it on every project. But it would be more awesome if it support background images. On 1.X version i edited the plugin so if it detects data-bgimg on wrapper span it adds image as background image on the wrapping span element. Maybe you can do something similar or even better?

**Comment by Etromania** [comment]
Another option that I have used is to hide the picturefill image with some css, then apply a load event on that image with js to get the image src it loads and apply it to a background of another element. It can get a bit dicy on the first load since the load event may have already fired so make sure to check if the image is already loaded. But for any time the picturefill changes based on the media queries on the source elements the load event is fired and you can replace the background image with the newly loaded image.

**Comment by mgp-novicell** [comment]
It's a shame you guys are so dismissive of using picturefill for backgrounds as using a css file is not an option if the background is user uploaded content. Not without generating inline css for each element, which frankly isn't a great solution.

**Comment by Wilto** [comment]
@mgp-novicell I agree that responsive background images are a pain with uploaded content—and I’ve used the same approach you describe, for want of something better—but keep in mind that Picturefill is a polyfill for a specific set of markup patterns. The features it offers are—and have to be, as a responsible polyfill—constrained to the set of features offered by those markup patterns.

**Comment by RussellBishop** [comment]
@QWp6t I like your approach - however, I do not like that you require JavaScript to achieve this. I have a solution that just uses CSS - what do you think?

https://codepen.io/russelllighthouse/pen/WXzENo
