### ISSUE TITLE
Should load new candidate in the background on environment changes

### ISSUE THREAD

**Issue by zcorpan** [scottjehl/picturefill#311]
"The user agent may at any time run the following algorithm to update an img element's image in order to react to changes in the environment."
http://www.whatwg.org/specs/web-apps/current-work/multipage/embedded-content.html#the-img-element

This algorithm fetches the image in the background, and only does the swap when it's completely loaded. If the load fails, it just drops it and doesn't change anything. This is different to what happens when setting .src. Setting .src makes the swap when the new image's dimensions are known, which can result in uglier result than waiting until the image is fully loaded.

picturefill always sets .src directly.

To preload, create a separate `img` and set its .src, then when it gets the `load` event, update .src on the original `img`. You could also make sure to not start another fetch if one is pending, like the spec does.

**Comment by Wilto** [comment]
This is squared-away in 3.0, yeah @aFarkas?

**Comment by aFarkas** [comment]
Partially yes. At the end it was a very academic issue, because the browser is already doing this automatically. If the image has a current request and a pending request, the browser shows the current request and loads the pending request in background. If the image has no current request, it loads it (hopefully progressive).

So this can be closed with 3.0

**Comment by zcorpan** [comment]
What happens if the new image fails to load? (Per spec it should continue to show the old image.)

**Comment by aFarkas** [comment]
@zcorpan 
Ok, didn't knew this. Is this only for ``srcset`` or can a ``source`` become invalid and we need to jump over to test the next ``source``? What happens if the initial candidate is broken? Do we re-start source selection to the next, until we find a suitable one?

I also tested this with chrome and Firefox, neither of those two are doing this.

**Comment by zcorpan** [comment]
No you don't jump to the next `source`. You just abort if the new candidate is broken (instead of showing alt text or so).

If the initial candidate is broken you show the alt text and maybe a broken image icon. You don't re-start or anything.
