### ISSUE TITLE
Picturefill 2 and Firefox 34

### ISSUE THREAD

**Issue by terraconnect** [scottjehl/picturefill#389]
It seems that I can't manage to make Picturefill work in Firefox (34.0.5) whereas it works in IE9-11.
Example can be seen here: http://formation.terraconnect.net/rwd/04_images/06_picturefill.html

Firefox throws me error: 
TypeError: setting a property that has only a getter in picturefill.min.js:4

**Comment by nessthehero** [comment]
Hoping someone sees this since this issue is closed, but I am also having issues with Firefox 34.0.5.

I am not getting an error message, it just doesn't work.

I'm confused as to the discussion about the config settings in Firefox. I don't understand why I would need to alter config settings on my local browser to get this to work. I can't instruct my client or their users to do this.

http://coe-berkeley-dev1.barkleylabs.com/

The two smaller features should switch out from a rectangle to a square image when mobile is reached, but only the square image loads for all sizes.

Again, no error message in Firefox's console, and both config settings mentioned above are set to "false".

**Comment by mike-engel** [comment]
@nessthehero Does it work if you change the `src` on the `img` to `srcset`?

**Comment by Wilto** [comment]
@nessthehero:

> I'm confused as to the discussion about the config settings in Firefox. I don't understand why I would need to alter config settings on my local browser to get this to work. I can't instruct my client or their users to do this.

This is an issue that should only come about if you’ve gone in and changed FF config settings in the first place—it isn’t something you’d run into with a stock install of FF.

This looks like an unrelated syntax issue, though: you’ve got `src` on the fallback `img` instead of `srcset`. That `src` is totally fine with native `picture`, but Picturefill needs `srcset` on the fallback in order to work around a double request: http://scottjehl.github.io/picturefill/#using-picture

**Comment by nessthehero** [comment]
Let my try that. I'll report back.

**Comment by nessthehero** [comment]
Okay, updated the image tag to use srcset instead of src, but the images are missing/broken now. Am I missing anything else?

Also, thanks @wilto for the clarification.

**Comment by mike-engel** [comment]
@nessthehero What version of picturefill are you using? Are you bundling it into main.js or home.js?

**Comment by nessthehero** [comment]
1.2.1, which I am realizing is probably my problem, yes? (honestly I thought I was using 2.0.0 so this is awkward)

It's bundled into respond.js

**Comment by mike-engel** [comment]
Yeah, seems like that would be the problem! 1.2.1 depends on the old syntax (using spans and what-not). 2+ will get you the spec which is what you're using. Can you update to 2.2 and see if the problem still exists?

**Comment by nessthehero** [comment]
The problem no longer exists!

Thank you so much for your time.

**Comment by mike-engel** [comment]
No problem, glad it got solved :smile:
