### ISSUE TITLE
loading picturefill with Browserify

### ISSUE THREAD

**Issue by mromanoff** [scottjehl/picturefill#410]
I have issues loading picturefill with browserify.
for example i require it:
require('picturefill');
or
var picturefill =  require('picturefill');
or
window.picturefill = require('picturefill');

i'm getting error message
Safari: TypeError: undefined is not a constructor (evaluating 'new this.Image()')
Firefox: TypeError: this.Image is not a constructor
Chrome: Uncaught TypeError: undefined is not a function
all fail on last line:  } )( this, this.document, new this.Image() ); 
if i change 'this' to 'window'. it works. I don't want to modify original library.
how i can properly pass a scope to this script?

**Comment by mike-engel** [comment]
Hey @mromanoff, this actually has been fixed in master ( 9f5279a7bb49a84aafb7cdb535ef12d15f963eb4 ), and will be released in 2.3.0. In the meantime, you can either manually edit the picturefill file in your `node_modules` folder, or grab a copy from the master branch to use. Until then, I'm going to work with the core PF team to see if we can't get a patch up to npm to fix it. Thanks!

**Comment by mromanoff** [comment]
@mike-engel thank you for quick response.

**Comment by nicholasjohn** [comment]
@mike-engel thanks for the solution. When do we think the NPM registry will be updated?

**Comment by mike-engel** [comment]
@nicholasjohn Hopefully soon. Once #420 is done, we can move super fast with this one.

**Comment by mike-engel** [comment]
@nicholasjohn @mromanoff Picturefill on npm should be updated now to 2.2.1 with this fix!

https://www.npmjs.com/package/picturefill
