### ISSUE TITLE
Avoid using findWidthFromSourceSize if possible

### ISSUE THREAD

**Issue by drynaski** [scottjehl/picturefill#471]
`findWidthFromSourceSet` and the inner call to getWidthFromLength is quite slow since it involves manipulating the DOM including changing styles and appending / removing the 'cached' element. This causes extra repaints, adds to thrashing, etc. Often the `sizesattr` is a simple pixel value or viewport value. If we can handle simple `sizesattr` values differently and use `findWidthFromSourceSize` for more complex `sizesattr`s, picturefill is much more performant.

In my fork I found that updating `pf.parseDescriptor` to set `widthInCssPixels` using the following code:
```
			 if(sizes.indexOf(' ') === -1 && (sizes.indexOf('px') === sizes.length - 2)) { // just 1 pixel width is specified, nothing fancy
			 	widthInCssPixels = parseInt(sizes, 10);
			 } else if(sizes === '100vw') { // just 1 viewport width is specified, nothing fancy
			 	widthInCssPixels = windowWidth; // (windowWidth is set on initialization and updated on resize)
			 } else { // something fancy
			  	widthInCssPixels = pf.findWidthFromSourceSize( sizes );
			 }
```
The site I'm using picturefill on doesn't make use of more-complicated sizes such as `(min-width:30em) calc(30% - 15px)`, and with this update handles rendering a page of images about 3x faster with this update.

Also, since it avoids using findWidthFromSourceSize altogether in two cases, it was causing the grunt test to fail due to this part of the test...
```
		pf.getWidthFromLength = function(width) {
			return 640;
		};
```
This seems like a hack of a test, I think it would be better to simulate a device viewport and change that during the test. But in case people do make use of overriding this method, throwing in a `!pf.getWidthFromLength()` in front of two overriding cases makes this approach work and makes the tests pass.

The browser tests also pass in IE, Firefox, Safari.

**Comment by aFarkas** [comment]
@drynaski 
We indeed need to improve performance for simple CSS sizes with vw, px and em units. And we work on this.

This is not a hack of testing. You want to do fine grained tests of one specific method without interference of another method.

In general, if anything bigger changes you also need to change the unit tests. But in your case, the test shouldn't be changed but your code instead should. Instead of adding your changes to ``parseDescriptor`` you can add it to ``getWidthFromLength``. 

While I believe you, that calc isn't used often, I actually doubt, that a lot of people are using just one simple pixel value or just '100vw' in the ``sizes`` attribute. In general you would see something like this:

``sizes="(max-width: 1280px) 100vw, 1280px"`` or ``sizes="(max-width: 480px) 100vw, (max-width: 1280px) 48vw, 600px"``


All this said: We have already an [alternate build](https://github.com/scottjehl/picturefill/blob/afarkas-pf3-proposal/dist/picturefill.js), that does calculate everything in JS without doing any DOM manipulation, due to some specific tests, it isn't 3x faster than normal picturefill, but it scales much better, so if current picturefill is slow, because you are using more than 10 images on one page you will have quite a speed boost. (Would be interested, how this performs for you).

**Comment by drynaski** [comment]
@aFarkas 
Thanks for the reply and reference to the alternate build, I'll check it out. I actually updated the PR to work with any vw value, but not with media queries like you show above. And yes, I understand that the use case you point out is more likely than a single vw value. Thanks again and I'll check out that build and let you know of the performance gains.
