### ISSUE TITLE
Double download when browser only has partial srcset support.

### ISSUE THREAD

**Issue by joemcgill** [scottjehl/picturefill#479]
While trying to implement a partial responsive image solution for WordPress, we've run across [an issue](http://ircbot.responsiveimages.org/bot/log/respimg/2015-04-01#T122198) where picturefill is causing a double download on browsers with only partial support for `srcset` (read: Safari and possibly the in development [Spartan](http://ircbot.responsiveimages.org/bot/log/respimg/2015-04-01#T122198) browser).

The markup pattern we're using is `srcset` + `sizes`, or roughly this:

```
<img src="path/to/image.jpg" 
    srcset="path/to/image.jpg 300w, path/to/image-600.jpg 600w, path/to/image-1200.jpg 1200w" 
    sizes="(max-width: 600px) 100vw, 600px" 
    width="600" height="400" alt="alt text" 
/>
```

I've created a test case to show an example of the markup and a possible no-src solution being used by The Guardian and others to work around this issue here: http://codepen.io/joemcgill/full/JoVVBv/

Currently, Safari on iOS will trigger a double download either way and Safari 8.02 will trigger the double download if a `src` attribute is present. I know there is no way to stop the browser from triggering that download, but it would be nice if there was a way to test for partial `srcset` support and _optionally_ bail on the second request if we know the first is going to be loading anyway.

**Comment by aFarkas** [comment]
This is a tough one. 

But I don't really get your indentation or I don't understand what you want to achieve. You still want to use an initial ``src`` attribute? And picturefill should still polyfill and create a double request, if a ``src`` attribute is used, while we should not polyfill, if the [Safari iOS bug](https://bugs.webkit.org/show_bug.cgi?id=135935) is detected? Why should we handle these cases different?

In combination with picturefill, I would suggest to not use a src attribute. Additionally see also [this markup pattern for iOS](https://github.com/scottjehl/picturefill/issues/438#issuecomment-75647795

In general a bug detect has to happen async and would look something like this:

```js
(function(){
	var loadBuggyWidth = false;
	var srcset = 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw== 9w';
	var img = document.createElement('img');
	var load = function(){
		loadBuggyWidth = true;
	};

	if(('srcset' in img) && !('sizes' in img)){
		img.srcset = srcset;
		img.onload = load;
	}
})();
```

**Comment by Wilto** [comment]
I asked @joemcgill to file this one so we could take a second look at `src` support. I want to research the gap between browsers with BG-breaking prefetching and browsers with native respimg support, because I’m wondering if we couldn’t bring back a little Just Use JavaScript™ to cover _some_ cases with `src`.

Chrome “broke” our original responsive images script on the Boston Globe site when it ramped up prefetching; same with Firefox shortly after. But I think _both_ were in “evergreen” turf by that point, and both will have native `picture` landing soon. Depending, we might be able to bring back an approach like the one we’re using on BG—which still works in older and less preparse-y browsers—and only risk the double download in the evergreens between “BG’s responsive images break” and “native `picture` support.”

**Comment by mike-engel** [comment]
ping @wilto and @aFarkas to checkup on if we want to try and handle double downloads.

**Comment by Wilto** [comment]
I spent a little time tinkering and thinking this over, and landed back where I started. I’m gonna close this one out for now, unfortunately.
