### ISSUE TITLE
Question : How to manage images inside a block with a max-width ?

### ISSUE THREAD

**Issue by messenjer** [scottjehl/picturefill#494]
Hello, I have a question.

I have a block with a max-width of 1200px.

* 2 rules : sizes&srcset :     

Rule 1 : with an image 100% of the block : sizes="(min-width: 768px) 50vw, 100vw"
Rule 2 : with an image 50% of the block : sizes="(min-width: 768px) 50vw, 100vw"

The following srcset : 

* srcset="http://placehold.it/360x203 360w,http://placehold.it/678x381 678w,http://placehold.it/1240x698 1240w" />

When the screen is 1680px large, "rule 2" displays the image in 1240px large, but the image max-width is 600px;

To force the max-size of the container, I updated the rule like this :

* sizes="(min-width: 1200px) calc(1200px/2), (min-width: 768px) 50vw, 100vw"

There is a better way to do that ? Is it advisable to use pixels for retina display ?

Regards

Mathieu

**Comment by baloneysandwiches** [comment]
`calc(1200px / 2)`

is an odd formulation, simply because it will always work out to 600px, under any media conditions. So you could just write "600px" instead.

Note that the final styled size of the image is still contingent on your CSS, which is another matter.

I'm closing this for now. Please reopen with a linked test case if you're still having trouble.
