### ISSUE TITLE
Latest update of Firefox does not work with jquery picturefill

### ISSUE THREAD

**Issue by yachtkeel** [scottjehl/picturefill#501]
I have a website where I use picturefill. Picturefill was working perfectly on all browsers including firefox until i updated firefox on mymac and windows 7, both versions of firefox does not work with jquery picturefill.

I checked jquery picturefill demo page: http://scottjehl.github.io/picturefill/examples/demo-02.html
The same problem there

Works fine with all oter browsers including chrome

**Comment by aFarkas** [comment]
In case you mean that the images don't change on resize, you can try this script:
https://github.com/scottjehl/picturefill/blob/afarkas-pf3-proposal/src/plugins/gecko-picture/pf.gecko-picture.js

This bug is already fixed in FF and will be likely released with version 39. For more information see:
https://bugzilla.mozilla.org/show_bug.cgi?id=1135812

In case this helps. Please close this issue.

**Comment by yachtkeel** [comment]
yes this is exactly what I meant,,,

Thank you for the reply and the solution.
