### ISSUE TITLE
Demo page does not loads proper 1x image for Desktop Chrome

### ISSUE THREAD

**Issue by poul-kg** [scottjehl/picturefill#543]
Desktop Chrome Version 43.0.2357.132 m

![ficturefill_issue_in_chrome](https://cloud.githubusercontent.com/assets/1153612/8667283/511c57ba-2a1f-11e5-8dae-b733f4a23b5e.jpg)

**Comment by Wilto** [comment]
Huh, right you are. Just tested on a 1x display, and extralarge is being loaded. Nothing too weird in the markup, either:

```html
<img srcset="examples/images/large.jpg 1x, examples/images/large.jpg 2x" alt="A giant stone face at The Bayon temple in Angkor Thom, Cambodia">
```

This might be a bigger issue than the docs, methinks.

**Comment by mike-engel** [comment]
Just tested with firefox and safari real quick, and they all perform as expected. Seems like a chrome issue to me.

**Comment by aFarkas** [comment]
I don't think this is an issue. Chrome's caching detection is kicking in. We can minimize false reports by using multiple different cache busters for all examples:

```html
<img srcset="examples/images/large.jpg?example1 1x, examples/images/large.jpg?example1 2x" alt="A giant stone face at The Bayon temple in Angkor Thom, Cambodia">
```

Additionally, it would be great if Chrome would take the smallest cached image, that satisfies the density, instead of simply the largest cached image (memory and CPU consumption).

**Comment by Wilto** [comment]
Okay, so, this is something interesting. It’s a native issue for sure, and I _assumed_ it was using the largest image in the cache consistently, which makes sense. However, reloading the page over and over again in a 1x environment _only_ I get the large source about 40% of the time. Is anyone able to try reproducing this?

**Comment by mike-engel** [comment]
Alright, more testing! Here's my setup real quick:

Laptop: 2x display
Secondary monitor: 1x(ish?) apple cinema display
Chrome: v43
Canary: v46

No matter which browser version, which display, incognito mode, force refresh, clear cache, the demo site will _always_ load the extraLarge image for me.

**Comment by baloneysandwiches** [comment]
Sounds like we're going to cache-bust image URLS in the demo. Here's a draft of language for the docs:

> “Modern browsers that support srcset natively may select a cached file that meets the minimum media condition, even if it is “overkill” for the current media condition. For example, a 2x file may be shown on a 1x device, if that 2x file is already in the cache. This is a native optimization to prevent unnecessary downloads. It’s typically encountered only on sites with multiple versions of the same image displayed in multiple elements at different sizes (like our demo page). For newcomers, we’ve worked around this somewhat surprising but correct behavior by adding a cache busting query string to the end of image file urls. You probably don’t need to do that, but understand that occasional selection of "oversize" resources, depending on the cache, is currently an expected behavior in Chrome, and you may encounter it during testing.”

**Comment by Wilto** [comment]
Oh, I’m an idiot; I know what the inconsistency was in my testing. I was looking at the index page locally, meaning that one of the _other_ instances of extralarge.jpg could have hit the cache before an instance of large.jpg—because of that, extralarge.jpg was getting pulled into the 1x/2x example _sometimes_.

I dunno if we should cache-bust, honestly—I feel like that could lead to more confusion when the native caching behavior is happening in the dev’s setup but _not_ in the Picturefill docs.

**Comment by Wilto** [comment]
(_Completely_ in favor of adding that language to the docs, though.)
