### ISSUE TITLE
Consider polyfilling the JS/DOM api portions

### ISSUE THREAD

**Issue by scottjehl** [scottjehl/picturefill#562]
Per a request from the FT, it'd be useful for them if we populated properties like `window.HTMLPictureElement` after polyfilling support for it. 

https://github.com/Financial-Times/polyfill-service/pull/448

Worth discussing if this will cause any difficulties with how things are set up internally, particularly on subsequent runs in a page?

**Comment by aFarkas** [comment]
We had basically two points:

1. We fix some issues in FF (fixed with FF 41), although FF basically supports full respimg.
2. picturefill core only implements the markup API. To mimic `window.HTMLPictureElement` we also need to fully polyfill the DOM properties and all relevant DOM mutations. This is done with our mutation plugin (https://github.com/scottjehl/picturefill/tree/3.0/dist/plugins/mutation). This mutation plugin has 4 flaws:

    a) no IE8 support (technically, quite impossible, we would need to use htc behaviors, which do not work cross-site and can cause crashes if used in combination with `Object.defineProperty`)
    b) The `img.srcset` getter might return an empty string in browsers which do support the x descriptor, but not the width descriptor. This flaw can be fixed for Microsoft edge and for Safari 8 for OSX, but we technically can't fix this for Safari 8 for iOS. (Apple is the only browser vendor, who prohibits overriding (=fixing) existing, but broken IDL attributes.) (`getAttribute('srcset')` is fixed in all browsers)
    c) `img.src` getter might return the image candidate on polyfilled browsers instead of the empty string. (we can fix this for all browsers, but we can't fix this for any version of Safari). (`getAttribute('src')` is fixed in all browsers)
    d) The mutation plugin is too large, to include it into the default core (if this is desired)

> Worth discussing if this will cause any difficulties with how things are set up internally, particularly on subsequent runs in a page?

Yeah, there would be some issues (especially with our plugins), but this is easy to fix.

I think this is pretty much it. I'm ok, with adding `window.HTMLPictureElement` to the mutation plugin. I don' think the downsides above will hit a lot of webpages.

But the big question is why is this necessary?

Couldn't do they check, whether `window.HTMLPictureElement` is implemented. If it is not, check whether ``window.picturefill`` is loaded, if no, load picturefill with mutation. If yes, check whether mutation plugin is added, if no, load mutation plugin?

**Comment by scottjehl** [comment]
great stuff, @aFarkas thank you.

I sympathize with your question at the end. Maybe it's a matter of consistency and not needing any lib-specific workarounds. Thoughts, @triblondon?

**Comment by triblondon** [comment]
Hi. The architecture of polyfill.io is designed to be generic, serving hundreds of polyfills.  To avoid maintenance hell, we impose some fairly basic constraints on polyfills:

1. The feature being polyfilled must be testable using a JavaScript expression that returns a boolean true in conforming browsers.  In this case, it's `"HTMLPictureElement" in this`.
2. The polyfill, when run in a non-conforming browser, must cause that browser to pass the simple feature test.

So, the problem here is that while picturefill does mostly polyfill the picture element it doesn't do it perfectly, and one of the inconsistencies between the native API and the one created by your polyfill is the name of the global that it creates.  Ideally, we believe, a polyfill should create no global objects other than the ones it is polyfilling.

We could work around the problem here by defining our detect as `"HTMLPictureElement" in this || "picturefill" in this`.  It's just that we prefer not to, on the basis that a) since the picturefill global is non-standard, it would contribute to a general inability for the `picturefill` global to ever be used for anything in a future standard, b) the API exposed by picturefill is not the same as HTMLPictureElement, but treating them as equivalently acceptable would imply that they are.

I know this might all sound terribly pedantic.  We live in fear of committing the [Mootools sin](https://esdiscuss.org/topic/having-a-non-enumerable-array-prototype-contains-may-not-be-web-compatible) of prematurely implementing something in a way that breaks a future standard.

**Comment by triblondon** [comment]
One other point: Developers using picturefill via the polyfill service will be unaware that they are using picturefill.  The idea is that they include `HTMLPictureElement` in the list of features they intend to use, and trust that we can make it work for them.  That's another reason why inconsistencies with the spec are a problem, no matter how well documented they are in your project.

**Comment by scottjehl** [comment]
@triblondon sounds reasonable for the service. That said, there are some good reasons picturefill has an API. Being able to manually reevaluate new markup for example (optionally within the scope of a subset of the DOM), which allows for broader support than relying on mutation listeners alone (there's an extension that does that but again, support isn't as broad). 

So, I'm not sure what to suggest in that regard. Keeping the API seems to be good for the usability of this project. Maybe picturefill isn't a good fit for the service?

**Comment by aFarkas** [comment]
@triblondon 

I think situation isn't clear at this point for us, because we are pedantic too. Unless we can't polyfill the API 100% correctly we have problems to add this constructor.

But there is good news for you. There is a lesser known DOM API to test picture support:

```js
'srcset' in document.createElement('source') && 'sizes' in document.createElement('source');
```

This API is polyfilled by the mutation plugin stated above. So if you include both scripts (core + mutation plugin, it should work).

**Comment by jonathan-fielding** [comment]
I will test using this using this instead of the original feature test I had in place,

**Comment by jonathan-fielding** [comment]
@aFarkas 

I will look at using this as the test tommorow when do couple more things to the pull request

Thanks for the help

**Comment by jonathan-fielding** [comment]
with picturefill in page "'srcset' in document.createElement('source') && 'sizes' in document.createElement('source')" still returns false

**Comment by aFarkas** [comment]
You need to include the mutation plugin. Here is an example: http://jsfiddle.net/qek32t4e/

```html
<script src="https://cdn.rawgit.com/scottjehl/picturefill/3.0/dist/picturefill.js"></script>
<script src="https://cdn.rawgit.com/scottjehl/picturefill/3.0/dist/plugins/mutation/pf.mutation.js"></script>
<script>
    alert(('srcset' in document.createElement('source')) && ('sizes' in document.createElement('source')));
</script>
```

**Comment by jonathan-fielding** [comment]
ah ok, will have to write something custom to merge the two files,

**Comment by jonathan-fielding** [comment]
Is the picturefill mutation available on npm?

**Comment by aFarkas** [comment]
Yes, with the version `3.0.0-beta1`.

**Comment by jonathan-fielding** [comment]
Is it wise to use beta1 in production?

**Comment by aFarkas** [comment]
> Is it wise to use beta1 in production?

In this situation absolutely. We will have an [RC1](https://github.com/scottjehl/picturefill/pull/559) soon.

**Comment by jonathan-fielding** [comment]
ok cool, I have done the changes and they are now ready for review by @triblondon, thanks for all the help

**Comment by jonathan-fielding** [comment]
Hi @aFarkas 

Quick question about the picturefill mutation, does it support IE9 and below, Firefox 3.6 and Safari 5.1?

Thanks

Jonathan

**Comment by aFarkas** [comment]
It uses mutationobserver and falls back to mutation events. Additionally it uses object.defineproperties. therefore support should be ie9, ff 4 and safari 5.1. No ie 8 support though.

**Comment by jonathan-fielding** [comment]
odd, the test isnt working in the browsers I mentioned, and the original jsfiddle you posted alerts false in firefox 3.6 http://jsfiddle.net/qek32t4e/

**Comment by mike-engel** [comment]
Quick check with @jonathan-fielding and @triblondon about the status of their work on this. Thanks!

**Comment by jonathan-fielding** [comment]
Hi Mike, 

The polyfill has been successfully implemented in the polyfill service and I myself have a site live using it so works really well. 

https://github.com/Financial-Times/polyfill-service/tree/master/polyfills/HTMLPictureElement

and the docs 

https://cdn.polyfill.io/v2/docs/features/#HTMLPictureElement

Really appreciate all of this teams help with this, by adding the picturefill polyfill to the polyfill service we are making it even easier for people to use picture element on their sites.

Thanks

Jonathan

**Comment by mike-engel** [comment]
Awesome, thanks Jonathan! Closing this out now.
