### ISSUE TITLE
2x images shown at half their native width

### ISSUE THREAD

**Issue by mattymess** [scottjehl/picturefill#575]
Given the following markup, I expect to se the 2x image displayed at it's full width when viewing on a HiDPI mobile device. However, when I view on Chrome's mobile dev tools, emulating as an iPhone 6, the image is displayed at half it's resolution.

A couple pertinent piece of informations...
  1. The `:medium` version is 320px wide
  1. The `:large`version is 640px wide

```html
<a href="<%= post.url %>">
  <picture>
    <!--[if IE 9]
      <video style='display: none'>
    -->
    <source media="(min-width: 768px)" srcset="<%= post.featured_image_url(:medium) %>, <%= post.featured_image_url(:large) %> 2x"></source>
    <img alt="<%= post.title %>" srcset="<%= post.featured_image_url(:small) %>, <%= post.featured_image_url(:medium) %> 2x"/>
    <!--[if IE 9]
      </video>
    -->
  </picture>
</a>
```

This is how it's displayed in the browser...It appears that picturefill is in face using the correct version (medium, 320px), but it's only taking up 160px of the viewport. 

What am I missing?

![image](https://cloud.githubusercontent.com/assets/1108825/9881656/ca8b6018-5b85-11e5-94b9-d14c2312a223.png)

**Comment by aFarkas** [comment]
I don't fully understand your problem, but I think you have wrong expectations about what should happen and how to use this. A short but nice introduction into respimg is this one: https://jakearchibald.com/2015/anatomy-of-responsive-images/

In general about your markup:

1. ``img`` has to be outside of the video tag workaround, otherwise IE9 won't display anything:

```html
<picture>
    <!--[if IE 9]
      <video style='display: none'>
    -->
    <source media="(min-width: 768px)" srcset="<%= post.featured_image_url(:medium) %>, <%= post.featured_image_url(:large) %> 2x"></source>
    <!--[if IE 9]
      </video>
    -->
     <img alt="<%= post.title %>" srcset="<%= post.featured_image_url(:small) %>, <%= post.featured_image_url(:medium) %> 2x"/>
  </picture>
```

2. While not needed I would use the following ``picture`` pattern:

```html
<picture>
    <!--[if IE 9]
      <video style='display: none'>
    -->
    <source media="(min-width: 768px)" srcset="<%= post.featured_image_url(:medium) %>, <%= post.featured_image_url(:large) %> 2x"></source>
   <source srcset="<%= post.featured_image_url(:small) %>, <%= post.featured_image_url(:medium) %> 2x"></source>
    <!--[if IE 9]
      </video>
    -->
     <img alt="<%= post.title %>"  />
  </picture>
```

3. The fact that you use one same image candidate in both different ``srcset``, tells me, that you don't use art direction and therefore you shouldn't use ``picture`` at all and your markup should than look something like this:

```html
<img 
     sizes="(max-width: 400px) 100vw, 400px"
     srcset="<%= post.featured_image_url(:medium) %> 320w,
        <%= post.featured_image_url(:large) %>  640w"
    alt="<%= post.title %>"  />
```

Note: I can't tell how your sizes should look like, this depends on your layout. In case you are too lazy for this you can try lazysizes with `data-sizes="auto"`.

------

Now to your question, I think everything works as expected. [A pixel is not a pixel](http://www.quirksmode.org/blog/archives/2010/04/a_pixel_is_not.html): If you provide a 2x image to a 2x device, it means that the browser has 4x more real pixels, than you count in layoutpixels (i.e. 2pixel horizontal x 2 pixel vertical). This also means an image with a physical width of 320 should be viewed with a width of 160 layout pixel on a 2x device to get the full quality.

**Comment by mattymess** [comment]
Thanks for the detailed explanation, Alexander. You're indeed correct, that my use case is not art directed and I definitely didn't completely understand all the different resimg implementations. I've since simplified things and have a much better understanding. Closing...
