### ISSUE TITLE
Add issue-making guidelines to CONTRIBUTING.md

### ISSUE THREAD

**Issue by mike-engel** [scottjehl/picturefill#591]
Since github asks uses to look at the contributing guidelines before making an issue, it would be nice to include a) a quick FAQ and b) a link to the website and some other info to consider before making an issue.

**Comment by jegtnes** [comment]
Some things that it'd be nice to have in there in addition:

- Giant disclaimer about the everlasting Firefox issue
- Is this a bug with Picturefill or with Responsive Images?
- The veritable bible of understanding srcset/sizes is a must-have: https://ericportis.com/posts/2014/srcset-sizes/
- A link to a place where people can ask rudimentary questions about responsive images to redirect them from PF issues, because, well, I can see why people can get confused if they haven't looked into it in much detail. Actually I'm not too sure where I'd go outside my company. Are forums still a thing? What year is this?
