### ISSUE TITLE
Fails to work on Safari

### ISSUE THREAD

**Issue by thisdeveloper** [scottjehl/picturefill#608]
Testing in Safari (latest on OSX) it fails to swap images and always just loads the biggest size.  Tested across multiple systems (3)

Even the examples on http://scottjehl.github.io/picturefill/ give the same result.

**Comment by mike-engel** [comment]
Hey @thisdeveloper, just tested with the latest safari (9.0.1) on el capitan (10.11.1), and it seems to work fine. A couple things to keep in mind when testing:

1. Make sure you start with a small window and go larger. If you start large and try to go small, the larger image will be used since it's already been downloaded.
2. Make sure to clear your cache before testing, and probably use a private window just to be sure.

If you're still seeing the issue after re-testing, please let us know.

**Comment by thisdeveloper** [comment]
Hi Mike. It just does not seem to work correctly either way.  In other browsers I can start large and scale down and it correctly swaps images from my desktop size to tablet and then mobile as I scale in.  This also works fine in reverse starting from the smaller size.

This is in an incognito window so no cache issues etc.

It only ever uses the first loaded image.

**Comment by mike-engel** [comment]
@thisdeveloper Is this a problem for you with all examples, only examples that use `srcset`, only only `picture` examples?

**Comment by thisdeveloper** [comment]
I use the picture and srcset method however I believe I did check all examples on the page I linked and they had the same issue.

**Comment by thisdeveloper** [comment]
Sorry I mean I use the picture method with srcset used for the images contained.

**Comment by aFarkas** [comment]
Can you please check on this site, wether it is changing the sources according to the viewport:
http://scottjehl.github.io/picturefill/examples/demo-02.html

If not, which image is shown? (extralarge, art-large or art-medium)

**Comment by thisdeveloper** [comment]
Interesting, I just tried it after coming home on the same macbook pro I used earlier - and it all seems to be working, in my project and on your example.   Very odd as it was happening on 2 other systems separately - will check again tomorrow morning.

**Comment by aFarkas** [comment]
Please re-open, if you can reproduce this and tell us how to do it. Thanks.
