### ISSUE TITLE
Clarification asked on double download gotcha

### ISSUE THREAD

**Issue by fchristant** [scottjehl/picturefill#613]
hi, I've read about the following gotcha:

"Trying to use the src attribute in a browser that doesn't support picture natively can result in a double download. To avoid this, don't use the src attribute on the img tag"

For a large website we're considering to kind of accept this gotcha and to just use the src attribute anyway, because it makes for a solution that is more SEO friendly, and in a way, it is ok to let some browsers have a slightly lesser experience.

That said, before making that decision it would help a lot to get the gotcha statement a bit more accurate, so that we make a well-informed decision.

- What does "can" mean? What are the conditions for a double download specifically
- Are there differences between the most popular browsers in this behavior?
- Double download, does it mean of the same image or of different image sizes?
- If it is the same image size (probably not) wouldn't it be cached anyway?

**Comment by aFarkas** [comment]
> What does "can" mean? What are the conditions for a double download specifically

If there is a `src` attribute and the browser does not support `picture` and `srcset`, the right candidate is loaded by the polyfill afterwards. If this is accidentally the same image src as specified in `src`, there is no double download, otherwise there is one.

> Are there differences between the most popular browsers in this behavior?

In general no. You can divide between browsers, that support only `src`, browsers that support only `srcset` at `img` and browsers that support everything including `picture`. If you use `picture` with `src` and `srcset` on your `img` element. You have this: 1. browser supports everything, everything is good. 2. supports `srcset` without `picture`, browser loads a candidate from `img.srcset` and might load a candidate from `source.srcset` triggered by polyfill. 3. browser supports nothing, browser loads `src` and then a candidate from a `srcset` triggered by polyfill.

> If it is the same image size (probably not) wouldn't it be cached anyway?

As I said, if it is accidentally the same image candidate, than no double download, otherwise you will have one.

All this said, google will index your images even without `src`, because picturefill is also executed by the google bot.

**Comment by fchristant** [comment]
Thank you so much, this clarifies a lot. @tclaeys.
