### ISSUE TITLE
Srcset and sizes demo not working as expected

### ISSUE THREAD

**Issue by carlotrimarchi** [scottjehl/picturefill#642]
I'm trying to get my head around responsive images with multiple srcset.

I tried the demo here: https://scottjehl.github.io/picturefill/examples/demo-01.html

Resizing the browser doesn't change anything, the image stays always the same. The second demo, the one with "picture", is working fine.
Can it be a problem on my side?

**Comment by jegtnes** [comment]
Hey @carlotrimarchi!

Without more information about your browser and environment we can't really look into this further, but some things to confirm:

- With `srcset`, if you've already got a larger resolution downloaded and cached, it will not swap this out for a smaller one when your viewport shrinks
- Ultimately, what source the browser chooses to display from a range of `srcset`s is entirely up to the browser, unlike `picture`, where you can set strict conditions. Theoretically, browsers could tomorrow roll out a bandwidth-saving preference which would _always_ select the smallest-resolution image in a `srcset`, even if you're on a retina Thunderbolt display.

The way the situation is right now, it depends a bit more, and browsers tend to be a bit conservative and request larger images rather than risk having to upscale a small image. So when I resize my Firefox instance down on a larger 2x density display, the particular example you're referring to in the docs will stay at a extra large resolution until you can't shrink the browser any further. However, if I move the window over to my 1x density external monitor, shrink it down, clear the cache and refresh, things are different. It'll start small but will then fetch the medium and large images as I scale up.

Does that clarify things? If not, please drop us a line with some more information (browser, screen size/density, screenshots/gifs of this behaviour happening) and we'll try to get to the bottom of it! :zap:

**Comment by jegtnes** [comment]
Oh, and one more thing: If you want to see more control over source selection (veering towards lower-quality images), you may be interested in checking out the _Source selection algorithm option_ section of the docs, or if you want _even_ more control, check out [Lazysizes](https://github.com/aFarkas/lazysizes/blob/gh-pages/README.md) and its [OptimumX] plugin(https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/optimumx).

**Comment by panec** [comment]
There is an issue with Safari 9.0.3 on Mac with example on: [https://scottjehl.github.io/picturefill/examples/demo-01.html](https://scottjehl.github.io/picturefill/examples/demo-01.html).

Event on resize does not trigger properly - the check for 

```javascript
if (!isSupportTestReady) {return;}
```
is always met and no image swapping happens. When page is reloaded it works.

**Comment by aFarkas** [comment]
@panec 
I'm not sure, what you mean here. 

For me it is working properly. Can you say, what image is loaded first and what image should be loaded on resize?

The demo actually works in Safari 9.0.3 native without picturefill.

**Comment by panec** [comment]
@aFarkas 
Assuming that you got your cache cleared **and** debug tools inside the window open I got the following result:
- narrow browser window -> large.jpg image
- resized to wide browser window -> large.jpg image
- reloaded page on wide browser window -> extralarge.jpg image

When I tried to replicate the same with debug tools open outside the window then the image was always extralarge.jpg even when the window width was 510px and dpr was x1, the same situation followed without debug tools open.

All screenshots done on Safari Version 9.0.3 (11601.4.4) OS X El Capitan 10.11.3

![screen shot 2016-03-14 at 13 50 39](https://cloud.githubusercontent.com/assets/2536779/13746600/085e93b6-e9ec-11e5-86f4-f3fd3e3e5f01.png)
![screen shot 2016-03-14 at 13 51 13](https://cloud.githubusercontent.com/assets/2536779/13746599/085dce54-e9ec-11e5-8f65-9d9d8220827c.png)
![screen shot 2016-03-14 at 13 51 29](https://cloud.githubusercontent.com/assets/2536779/13746601/085f097c-e9ec-11e5-9f2f-e06f529bb30c.png)
![screen shot 2016-03-14 at 13 52 08](https://cloud.githubusercontent.com/assets/2536779/13746602/086235ac-e9ec-11e5-8fa1-84e59a72699e.png)

**Comment by aFarkas** [comment]
@panec 

This is a bug/feature of the native implementation. I will look into it.

**Comment by ymages** [comment]
same here picture + source are working as expected but not srcset
when screen is resized the image doesn't change with chrome and safari but it works with firefox (all browsers last version today)

`<img src="images/1000/1.jpg" srcset="images/200/1.jpg 320w, images/1000/1.jpg 800w, images/1500/1.jpg 1200w, images/2500/1.jpg 1600w">`

```
img{
	max-width:100%;
	width:auto;
	height:auto;
}
```

**Comment by mfazio26** [comment]
Ran into the same problem, struggled for a while and could only find the link below. Assuming this is what @aFarkas is referring to regarding a "bug/feature of the native implementation".
https://bugs.webkit.org/show_bug.cgi?id=149899

I could be misinterpreting this, but it appears Safari is spec compliant (full support for `<img>` srcset/sizes) even though it only chooses a single resource on initial load and does not update on viewport changes/resizes. And, `<picture>` works fine because we are literally telling the browser what to do an when.

That said, in my opinion, the Picturefill/Chrome/Firefox implementations are better and "what we expect", and appears it will be added (someday) in Safari. 

Question is, is it possible for Picturefill to detect whether a browser will update on resize? And if it won't, Picturefill kicks in and does its thing?

**Comment by aFarkas** [comment]
@mfazio26 
We could only add some heuristics to detect this problem. But we don't have a clear way to do so. And additionally we would need to run picturefill in all browsers and compare our source selection with the native source selection. Which means we need to penalize all users.

And yes, you are right. Safari's behavior is spec compliant, but not really desired.

**Comment by aFarkas** [comment]
@mfazio26 
Just re-thought this. We had some similar problems with early implementations in FF and we could fix those by changing attributes to force a resource selection. See here: https://github.com/scottjehl/picturefill/blob/master/src/plugins/gecko-picture/pf.gecko-picture.js

Maybe Safari would need other attributes, but this could be tested. This still just leaves us with the problem how can we detect the problem?

**Comment by mfazio26** [comment]
@aFarkas I have to think about this a little more, but if I'm understanding that module correctly, that's really close, right? What would happen if (I haven't tested it) – instead of waiting for a resize event to see what happens, you programmatically changed the `sizes` to something you know would/should trigger a change? But, I'm guessing that wouldn't work. Forcing the attribute change would probably force a re-render, and even Safari would probably update...giving you a false positive. Hmm.
