### ISSUE TITLE
I don't want to change the original src for srcset. Is better way to deal with it?

### ISSUE THREAD

**Issue by alexanmtz** [scottjehl/picturefill#643]
Well,

I'm using picturefill, but I would like to keep the original src attribute to have a semantic html. If i juste make something like this before the polyfill starts(I just made with jQuery for example purposes, we could easily do with querySelector too):

$('img').each(function(){
	var source = $(this).attr('src');
	$(this).attr('srcset', source);
	$(this).removeAttr('src');
});

This way it would fire double download?

**Comment by jegtnes** [comment]
Hey there @alexanmtz,

Thanks for getting in touch! This probably isn't the best way to approach things, though. If semantic purity is your main concern, this document will become invalid once that JS has got a hold of it. As well, we recommend loading Picturefill asynchronously as soon as possible. If you do this, there's a chance of Picturefill finishing execution before the document tree is ready to be parsed (`document.ready()`), and since your proposed script here will execute _before_ Picturefill, there's a chance your document tree won't be ready, which means it'll apply this to maybe some images, but not all. 

So all things considered, this is brittle. There're a couple of solid ways you can solve this, though, so fear ye not! Something to note beforehand: `srcset` support is actually getting pretty solid. (85% support in Brazil right now 💪🏼) — although, of course, your actual target market may vary. But it's a good baseline!

If semantic purity and strict adherence to the spec is your main concern, these are your options:
You can either provide a normal `src` with a valid image source in addition to the `srcset`, and risk a double download in the 15% of browsers lacking native srcset support

Alternatively, my favourite solution is to provide an empty placeholder gif inline in your `src` attribute:
`<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" srcset="rad-wolf.jpg 200w, uber-rad-wolf-hd-retina.jpg 400w" alt="A rad wolf">`
This is valid HTML and won't fail any validation. Unlike empty sources (`src=""`)or invalid inline Base64s (`src=data:image/gif;base64,WHARRGARBL`, this also won't throw any weird browser errors, as the previous inline base64 gif is a very small transparent image.
This works for:
- srcset-supporting browsers (85%)
- non-srcset supporting browsers whose JS-execution succeeded (14.835% (~98.9% of 15% ([source](https://gds.blog.gov.uk/2013/10/21/how-many-people-are-missing-out-on-javascript-enhancement/))))

The remaining 0.165% of your visits will be stuck with the alt text.

Hope that helps, my dude, but if you have any further questions please do reply back! Have a rad day. 💯

**Comment by alexanmtz** [comment]
Thanks for all the clear information @jegtnes. The jQuery code it was just a illustration of a more accurate and general solution to accomplish a Picturefill Polyfill "pure". The main message it was: If I just change the src attribute to sourceset via js it could avoid the double download and make a more unobstrusive picturefill? With a positive answer of this, I would thing a better way to integrate this inside de picturefill code. But I imagine that this couldn't avoid the double download, because the image source would be downloaded as the document loads and before change the attribute(that's what I suppose to).

Keep the source and sourceset in image attribute it would be a really great solution. And I appreciate and thank you for this advice. Thats the one that I will use.

The semantic is really a concern to me and this feature (use of image tag with source, as it is) would make picturefill a better polyfill. Use a empty gif I don't think a good solution because the original image is a empty gif and the original image it should be the one.

I'm not a fascist semantic guy :p . It's just that I think there's benefits to make the HTML "original", that JS is a layer of enhancement. For example, in a project that I was working of price comparison, I should scrap to find prices in other sites, and one of them return instead of the original images a loading replacement because they use the loading image as the source. I think the page have to keep the original structure and not to be so JS dependent. But for this is depending on the case.

**Comment by jegtnes** [comment]
Hey again!

I totally understand the point of using JS and polyfills entirely as a progressively enhanced layer. Generally, it's more reliable and robust. That being said, I'm not 100% sure about the technical feasibility of doing this kind of source swapping, though, I haven't worked extensively on Picturefill core myself (but a lot of very smart people have).

I'm not sure I understand your use case, though, so let me try to get to the bottom of this.

There are three distinct and different use cases for responsive images, but let's look at the two relevant to us here:
1) To serve the browser an identical-looking image at various different resolutions so you don't need to download an image much bigger or much smaller than you need. This is the equivalent of having smaller meal portions for children at a restaurant (except instead of asking you what you want, the water will automatically assume your children want the smaller meals by default (this is possibly a terrible analogy)). For this, you use the `srcset` and `sizes` attributes on an `img`, and the browser does some guess work to assume which version is right. No `picture` necessary! :bomb:
2) To serve the browser a different version of the image entirely at different viewport widths. These could be different dimensions, different sizes, or possibly different images entirely. This is called art direction. For this, you use the `picture` element, combined with one to several `source` elements with the `srcset` attribute (if you try to apply `src` to a `source` inside a `picture`, it will be ignored) and one `img` tag. The reason we apply the `srcset` to the `img` tag is as a fallback so that browsers that don't understand `source` elements but understand `srcset` (like Android 2.3) can still benefit from _some_ responsiveness. Progressive enhancement! ✨

More information here: http://alistapart.com/article/responsive-images-in-practice

In either case, if you are using `picture` and want to replace the `src` with a `srcset` with JS as you described earlier: If there's only one image source in `srcset` (as there would be if you renamed `src` to `srcset`), I don't think you need to use `srcset` at all, as good old `src` will serve the same purpose and be universally understood. If there are multiple images in `srcset` alongside the `src`, these will be overridden by the `src` -> `srcset` replacement you suggested, so you may be doing more harm than good.

As I said, I'm not 100% sure about your use case, so if I got something wrong or this doesn't clear things up, let me know!

**Comment by alexanmtz** [comment]
Hi @jegtnes,

Thanks again for all clarification. I guess now I have a overall understanding of all use cases. I'm now using picture, with a image src attribute to works clean and keep the semantic and the srcset attribute in the same img and I'm getting great results. I will try the solution 1! (And the analogy it was not so terrible, but even fun :-)

**Comment by jegtnes** [comment]
Hey dude! No worries :) Glad you managed to figure things out. We're here if you need anything else. ⚡️
