### ISSUE TITLE
Proposal: Client Hints Polyfill

### ISSUE THREAD

**Issue by kellysutton** [scottjehl/picturefill#645]
[Client Hints](https://github.com/igrigorik/http-client-hints) landed with Chrome 46 in October 2015, and could use a polyfill. Because Client Hints are primarily image-centric for now and are another tool for implementing responsive images, I think Picturefill is the most logical choice for where to land such a polyfill.

Client Hints can require a bit more sophistication to implement on the server-side, due to the wide variations in potential `Width` values. CH will work best with a back-end capable of dynamic image resizing such as [Thumbor](https://github.com/thumbor/thumbor), [Akamai Image Converter](https://www.akamai.com/us/en/solutions/products/web-performance/cloudlets/image-converter.jsp), or [imgix](https://www.imgix.com). (Disclaimer: I work for imgix.) Each of these services operates on the same principle: They allow you to manipulate images arbitrarily by changing the URL's path or query parameters.

Generally, I find Client Hints to be a great as an implementer because it greatly cuts down the code required to implement responsive images.

## Proposed Functionality

When [Client Hints support is advertised with a HTML meta element](http://httpwg.org/http-extensions/client-hints.html#advertising-support-for-client-hints), activate the Client Hints polyfill.

This will functionality will augment the [`getCandidateForSrc`](https://github.com/scottjehl/picturefill/blob/master/src/picturefill.js#L350-L363) to generate a properly-modified src URL. It would be up to the users to define a `transformSrcGivenWidthAndDPR` or similar method to manipulate URLs according to each back-end services' expectation. Picturefill could offer drop-in support for Thumbor, imgix, et. al via different plugins.

For example, the `transformSrcGivenWidthAndDPR` method might look like the following:

```js
// Transforms given `width` and `dpr` into query parameters appending
// to the `src`
transformSrcGivenWidthAndDPR: function(src, width, dpr) {
  var queryParamSeparator = src.indexOf("?") === -1 ? "?" : "&";
  return src + queryParamSeparator + "w=" + width + "&dpr=" + dpr;
}
```

If this sounds interesting at all, I'll take a crack at a Pull Request!

**Comment by jegtnes** [comment]
Hey @kellysutton,

We're obviously very interested in the developments of client hints and how we can help get those to a wider audience, including the users of image-processing-as-a-service services! That being said, it may not possibly be in the _core_ remit of Picturefill, which is "make `<picture>` and `srcset` Just Work In All The Browsers You Can Throw At It"; because it sounds like this would either intrinsically be tied to third-party services or need tailoring to your own server's URI syntax expectations. But that doesn't mean we wouldn't love to see this as a plugin! We've got a range of plugins already serving up some non-core-but-still-really-useful-if-you-need-them use-cases, such as the intrinsic dimension plugin, the DOM mutation listener, and the additional-MIME-type-support plugin, and it'd be rad to have client hint support alongside those!

If you're still interested, a PR would be a superb avenue for further discussion. :+1: If you need to modify/extend some core functions of Picturefill to make this happen, that's cool.

Oh, and if you haven't already, it may be worth reaching out to @igrigorik to chat about how we can make this work the best we possibly can—I'm sure he'd have some light to shed on how to make this happen.

**Comment by yoavweiss** [comment]
I think that since such a polyfill requires the markup to not have any `src` *or* `srcset` attributes in it, it's not something that can work alongside the traditional polyfill model, where the same markup targets both supporting and non-supporting browsers.

On the other hand, the [lazysizes](https://github.com/aFarkas/lazysizes) project (which does match these requirements might be a better home for a Client-Hints-inspired URL transformations, as you propose.
You could even couple it with a SW that will translate these URLs into standard Client-Hints.

**Comment by kellysutton** [comment]
Yep, already chatting with @igrigorik and @yoavweiss through other channels. I think Yoav is right here: lazysizes would be a much better avenue here for implementation. 

Thanks for the input! Closing this issue.
