### ISSUE TITLE
Chrome 51 loads JPEG 2000 images with typesupport plugin

### ISSUE THREAD

**Issue by dstaley** [scottjehl/picturefill#657]
When using the typesupport plugin to deliver browser-appropriate images, it looks like Chrome 51 is making network requests for JPEG 2000 images. This occurs even without picturefill, so I'm not entirely sure it's something that picturefill can prevent, but I wanted to at least report it.

I've made a quick demo [here](http://output.jsbin.com/nolowop).

**Comment by aFarkas** [comment]
Unfortunately at the time picturefill is executed the browser has already made his request.

The only thing you can do, is to swap your `source` elements, so that the webp is before the jp2 image. 

It would be great if you can file a [chrome bug](https://bugs.chromium.org/p/chromium/issues/list) and paste the link here for cross tracking.
