### ISSUE TITLE
Polyfill currentSrc

### ISSUE THREAD

**Issue by bfred-it** [scottjehl/picturefill#659]
Is there any plan to polyfill this property? There's `.curSrc` but that isn't evaluated in Safari 8 and Edge 12 since they support `srcset`

**Comment by mike-engel** [comment]
I don't believe so, but @aFarkas can clarify.

**Comment by aFarkas** [comment]
Our polyfill is part of the mutation extension: https://github.com/scottjehl/picturefill/blob/master/dist/plugins/mutation/pf.mutation.js#L331-L401

**Comment by bfred-it** [comment]
Cool, it does seem to work on Safari 8 and Edge 12 in my [test](http://codepen.io/anon/pen/vKjdrO?editors=0011) I wonder if it belongs to a plugin though since `currentSrc` still matters if the src doesn't change

**Comment by aFarkas** [comment]
@bfred-it 
The name mutation plugin is here a little bit misleading. The mutation extension includes all JS APIs, while the core only implements the markup API. (For example the `srcset`, `media` and `sizes` IDL attributes are also polyfilled with the mutation plugin.) Additionally the mutation extension has a different browser support, because it needs an ES5 environment.

**Comment by bfred-it** [comment]
Gotcha, that makes sense

**Comment by julmot** [comment]
`currentSrc` doesn't seemt to work for me in IE11.
