### ISSUE TITLE
Browers issues

### ISSUE THREAD

**Issue by ricnunes** [scottjehl/picturefill#660]
Hello,

I seem to be having some issues on different browsers, hope you can help me.

what I'm using: 
` <img sizes="100vw" srcset="biggest_image 977w, tablet_mobile_image 767w, mobile_image 480w" />`

version of picturefill is 3.0.2, but it also happened on 2.3.1

On Chrome, the images behave as intended, although when reaching the breakpoint from a bigger breakpoint, I need to refresh the page in order for it to show the other image, but if I resize from the smaller breakpoint to the bigger one, it changes automatically.

On IE 10 it behaves correctly when resizing up and down
On IE 11, Safari and Firefox it shows the 767w image until 480px and the 977w image across all the other sizes.

Am I doing something wrong?

**Comment by jegtnes** [comment]
Hey @ricnunes,

This isn't an issue with Picturefill, per se, this is how browsers generally handle `srcset`. `srcset` is designed for handling _just_ multiple resolutions of the same image to save bandwidth. Chrome doesn't bother downloading the smaller image if it's been shrunk down, because it has the bigger image in the cache and will shrink that instead to save you bandwidth. This is a good thing. This may also change a bit in the future, and it will vary a bit depending on browsers, as they're still figuring it out.

If you need more granular control over exactly what images are displayed at a certain resolution, [you'd want to use `picture` instead](https://scottjehl.github.io/picturefill/#using-picture). Hope that helps!

**Comment by ricnunes** [comment]
Thank you :) I wasn't using `picture` because I thought it was less compatible.

**Comment by jegtnes** [comment]
Natively, yes, `srcset` has very slightly broader browser support (although only by about 3 percentage points globally), but Picturefill polyfills both `<picture>` and `srcset`. 👍

**Comment by ricnunes** [comment]
It worked perfectly with the `picture`, thank you.
