### ISSUE TITLE
Windows 10, ie11 and Chrome display different images.

### ISSUE THREAD

**Issue by rantiev** [scottjehl/picturefill#661]
Hi, in IE11 i see flash of bigger image (300x300) and than 300x300 appears again but in less width. In Chrome there is 800x300 image. Zoom 100% in both browsers. No any device emulation in chrome.

What could be wrong? Have used code from your website note from the repo.

Source is:
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>raLoader</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<script async="" src="picturefill/plugins/intrinsic-dimension/pf.intrinsic.min.js"></script>
	<script async="" src="picturefill/picturefill.min.js"></script>
</head>
<body>
	<img srcset="../lazyloading/imgs/800x300.jpg 800w, ../lazyloading/imgs/300x300.jpg 640w" sizes="(min-width: 1024px) 10vw, 100vw"/>
</body>
</html>
```

**Comment by rantiev** [comment]
By far i think that best thing is to use img tag with src for ie, without srcset support at all, without your polyfill that it seems doesn't work.

**Comment by aFarkas** [comment]
The polyfill is working fine.

We can try to minimize this flash in case someone is using invalid markup like you do, but if you would use valid markup with width descriptors, there should be no flash.

Also note, that you have obviously wrong expectations if you think, that IE with picturefill has to load the exact same image like Chrome does. If you test in FF, Safari and Edge you might see, that some of these browsers (all of those support `srcset` natively) will load the same image as IE with picturefill polyfilled.

**Comment by rantiev** [comment]
So what is the valid markup? Could you fix my source? It's not 1000 lines.

So you wrote that i might have wrong expectation that all the browsers Chrome and IE  + polyfill image should use the same image and in the next sentence wrote that some browsers Chrome and Edge will load the same to IE + polyfill image. I can't understand this...

Don't images in Chrome and IE + polyfill be the same in the same viewport width and with no any devices emulation? Why? Do you think it's right thing?

**Comment by rantiev** [comment]
Ok, now i have the same images by default. In Chrome i had to close tab and open it again, because it showed old image there.

And sometime flash is not significant in IE + polyfill. I still didn't get what you wrote about width descriptors. 

It you meant width image attribute, we have responsive images it's hard to say what should be the width value, and if there is no flash in desktop then we will got flash in mobile screens. Am i wrong?

**Comment by aFarkas** [comment]
1. You are not allowed to do art direction inside of `srcset`. If you need art direction use `picture`.
2. The width descriptor describes the physical width of your image candidate. (You used 640 for a 300 image, which is responsible for the flash.)
3. Your `sizes` attribute didn't made too much sense. Although it is impossible to know, what you want. I tried to change it up to something more reasonable.

```html
<img srcset="../lazyloading/imgs/800x300.jpg 800w, ../lazyloading/imgs/640x240.jpg 640w" sizes="(min-width: 1024px) 640px, 100vw"/>
```

With `srcset` the browser is free to choose the image candidate based on different algorithms depending on the situation. Every browser can run a different algorithm. Because often there are more than just one reasonable image selection result, browser might differ in the exact image candidate. 

In general picturefill runs a similar algorithm like Chrome, but Chrome additionally favors all cached images, which yields to the situation, that a normal developer will often see the largest one loaded in Chrome, if she/he doesn't clear the cache.

**Comment by rantiev** [comment]
I was doing experiments with sizes attribute, whether trying to see how it's handled, what image will be shown etc.

Thanks for your time, now it's clear.

**Comment by aFarkas** [comment]
Happy to help.
