### ISSUE TITLE
Problem with element properties in IE11

### ISSUE THREAD

**Issue by iboargun** [scottjehl/picturefill#673]
There is a problem with IE11 if element is not accessible or has no properties.
I have a bugfix already for it and would appreciate if you can fix it soon with newer version, because we need to fix this in one project where it appears. thanks

// Loop through all elements
for ( i = 0; i < plen; i++ ) {
++     if(elements[i])
              pf.fillImg(elements[ i ], options);
}

**Comment by aFarkas** [comment]
Thank you for your bug report. We would need a test case or at least a link to the project to reproduce this specific bug.

**Comment by iboargun** [comment]
@aFarkas can't provide project link because it's in development and not public yet. 

But bug is simple: If there is no elements[i] defined it throws a problem on IE11.
I don't know in which context this appears...

**Comment by jegtnes** [comment]
@iboargun Can you attempt to recreate just the problem in the simplest way possible in something like CodePen or JSBin? The reason we ask for a test case is because we don't have the time to attempt to recreate every bug reported; especially as Picturefill's at the stage of maturity where we don't often see new bugs crop up, especially in a fairly heavily tested browser such as IE11. It helps us help you, basically 😊
