### ISSUE TITLE
Safari - Images don't load after appending by infinite scroll 

### ISSUE THREAD

**Issue by tiagogon** [scottjehl/picturefill#687]
I am using on my website the [infinite-scroll.com](infinite-scroll.com).

Everything works fine on Chrome and Firefox. 

But on Safari once the thumbnails are appended, the images do not load. 

You can see it on this images or live [here](https://trouble.place/m/photography/). 

![screen shot 2017-07-21 at 20 06 30](https://user-images.githubusercontent.com/3286869/28476408-38240c54-6e50-11e7-9fde-066ac6d8429d.png)

does anyone know how to solve this? 

I thank you in advance!

**Comment by tiagogon** [comment]
I got [this contribution](https://github.com/metafizzy/infinite-scroll/issues/694#issuecomment-317105002) but still does not work.

**Comment by modeckimellett** [comment]
I was seeing a similar issue in Chrome and Firefox with appended content. I was able to force a redraw by firing a fake window resize event. I used the following:
```
var resizeEvent = window.document.createEvent('UIEvents'); 
resizeEvent .initUIEvent('resize', true, false, window, 0); 
window.dispatchEvent(resizeEvent);
```
From this StackOverflow answer: https://stackoverflow.com/a/1818513/1007661

I tried this because of the info regarding deferred loading at the end of an old version of the README: https://github.com/scottjehl/picturefill/blob/a3344289ea535b58cb2460fed62c65e15deb1068/README.md

Note that I'm still on v2.3.1 of picturefill. So you might see different results.

**Comment by tiagogon** [comment]
still doesn't work on my case.

**Comment by modeckimellett** [comment]
I checked for differences and my use case is different from yours. I'm using the `<picture>` syntax to provide completely different pictures at different screen sizes. It looks like you're using the `<img srcset size>` syntax. I guess the fix I have only works with the `<picture>` syntax which seems odd.
