### ISSUE TITLE
Firefox Loads 2x Retina Images (other browsers DON'T)

### ISSUE THREAD

**Issue by lucasw87** [scottjehl/picturefill#713]
Hey there, I have a problem with serving 2x pictures on retina displays. There's no issue when loading retina images on mobile devices and tables but rather on my monitor, which is a **23.8", 16:9, 2560x1440.** 

Yes, it's not exactly retina, but the thing is that I use Windows 10,  and I use **scaling (120%)**, which makes all the apps and sites larger than they actually are, to make them more easily readable with that resolution.

The thing is that when I visit my site, the images become blurry and the 2x retina versions of the pictures don't load. That's in Opera and Chrome.

**Firefox**, on the other hand, handles it perfectly. When you scale up, it loads retina images and nothing looks blurry. When you scale down it jumps back to non-retina images. 

Below, you can see the screenshots: 1st is Chrome, 2nd is Firefox:

![1](https://user-images.githubusercontent.com/53819340/62535885-3c01e980-b855-11e9-87d6-cf68bc77bd0e.jpg)
![2](https://user-images.githubusercontent.com/53819340/62535897-40c69d80-b855-11e9-8a66-567671c5a0ca.jpg)

I'm wondering why that happens, and what I can do to serve retina images on high resolutions that use scaling (I'd like Chrome and Opera to behave the same way as Firefox does)

**Comment by lucasw87** [comment]
Anyone? I've spend like 8 hours researching this, but couldn't figure out what's going on. Any help would be highly appreciated!

**Comment by aFarkas** [comment]
@lucasw87 
This is not a picturefill issue but a browser issue if specified this way. Chrome, FF, Safari and Edge all support `picture` and `srcset`. So you would need to fill a browser bug.

From my testing zooming in FF and Chrome does also change the `devicePixelRatio` so it should also affect image loading in both browsers. In Safari it doesn't. But I haven't tested directly with responsive images.

If you report a browser bug. Please share the link here.

**Comment by lucasw87** [comment]
aFarkas, thanks for your reply! I just checked the **devicePixelRatio** in all 3 browsers and they all show 1.25. 

I then scaled up Opera and Chrome even more (125%) so that the pixel ratio became 1.56 and refreshed the page, and only then they loaded retina versions images. 

So it seems that Firefox loads retina images as soon as the pixel ratio goes beyond **1**, while Opera and Chrome only load retina images when the pixel ratio rate exceeds **1.5**. 

Do you think I should report that? Is that considered a normal behavior?

 I can't be the only one who have noticed it, but there's no info on this online whatsoever!

**Comment by aFarkas** [comment]
> I can't be the only one who have noticed it, but there's no info on this online whatsoever!

Probably not but in detail maybe yes.

Fun fact: Only from description I know exactly the problem what happens. (And for me it's kind of a told ya moment ;-)).

The problem is the following. If you have a device with 2x and you have two image candidates say one has a calculated density of 1.8 and the other has a calculated density of 2.3 which should the browser take? FF will always take the 2.3 while Chrome takes the 1.8 image.

In the example above Chrome decides the right way (of course there will be always edge cases where 1.8 wasn't enough). But as soon as you go to the lower end of devices let's say you have a device with 1x and an image with 0.8x and another with 1.3x. The browser should choose the 1.3x. And in fact chrome does this too. But the algorithm for this is too simple.

Chrome simply disables the performant image candidate selection for devices with 1x or lower. This yields to the strange situation, that as soon as the device has a 1.01x chrome would choose the smaller image.

How can you fix this? If you provide an image candidate that is bigger as the currently chosen one but smaller as the one you expect chrome to load, Chrome will load it.

Should this be fixed in Chrome? I think yes!

I have written a small tool to compare my favorite source selection model with current chromes model. You can find it here: http://jsfiddle.net/trixta/9dponzs2/

As already described as long as the device dpr is 1. Chrome doesn't  do anything smart here.

Due to the fact that I'm shit in Math I couldn't provide a great algorithm I simply just tweaked some crazy code until the numbers that matter most 1-4dpr device make sense (after 4 it really doesn't make too much difference).

The basic idea of my algorithm compared to chrome is the following:

1. The most important dpr to consider in the formula is the dpr of the lower image candidate
2. If the dpr of the lower image candidate is 1.6 the result should be similar to the arithmetic mean calculation that Chrome uses. But as soon as the lower image candidate drops below 1.6 it should tend to take the higher candidate compared to an arithmetic mean calculation (in an exponential way). This goes also the other way around as soon as the lower image candidate is bigger than 1.6 it should tend to take the lower one compared to a arithmetic mean calculation.

So how can this be fixed?

Quick fix:
Instead of finding a great formula that implements something that I described above only take my 1. idea of the algorithm into account. Instead of disabling the "performant" source selection based on the dpr of a device (currently 1). Use the dpr of the lower image candidate to decide wether the "performant" selection should be run. (Probably it should use also a higher number like 1.2 or similar).

To be sure: Could you please post here the dpr of the two images (The image that is loaded and the image that you expect chrome to be loaded). In case you don't know how to calculate.

Simply check what the calculated `sizes` attribute means in pixel and then post the two `w` descriptors for the two images.

**Comment by lucasw87** [comment]
@aFarkas 
I really appreciate your thorough reply! Not that I understood much from it :) I'm not a programmer and am quite new to these things.

I understand what devicePixelRatio is, but I don't quite get what is a DPR of a picture and how to calculate it. 

My site is PianoDreamers.com

For example, for my logo (in the header) I use a 550px wide picture. For most of the pictures I also load a retina version (usually double the resolution of the original non-retina picture, sometimes a bit less).  So for the logo I have a 550px picture and then a 2x retina version (1100px) that should be loaded when the devicePixelRatio is over 1.

When I view my site on my laptop (17.3 inch 1920x1080 px), the pixel ratio is 1 (the scaling in Windows 10 settings and browser settings is set to 100%), and all images display in their original size (non-retina). 

But, when I connect the laptop to my monitor (23.8", 2560x1440) I have to turn on App Scaling in Windows settings to make things bigger (I set it to 120%), which automatically increases my devicePixelRatio from 1x to 1.2x, and I expect the 2x retina pictures to load but only Firefox does it and the rest of the browser load the 1x original version.

**Comment by aFarkas** [comment]
@lucasw87 

I checked your side and while the described problem is exactly what I thought of. My "improved" algorithm wouldn't help you either (although it is very close. with a browser dpr of 1.2x and a lower candidate of 1x and a higher candidate of 1.9x my source selection would indeed choose the 1.9x.  While in Chrome you would have to provide a 1.4x  image or smaller to get the bigger image selected.) At the same time the quick fix for chrome described above would help you.

At this point I can only tell you this: The browser is free to choose the candidate the browser thinks is best from a quality/performance standpoint. While FF doesn't have anything smart here, Chrome trades performance against quality. You have "only" optimized for 1x and 2x devices and now you complain that there is no perfect image for a 1.2 device.

The only current solution for you: Provide either a third new 1.2-1.4 image candidate or replace either the 1x with a 1.2x or replace the 2x with a 1.4x candidate. Or if you totally lazy simply describe the 2x image as 1.4x image.

@yoavweiss 
I probably go on your nerves, but could you re-think about [my described source selection algorithm](https://github.com/scottjehl/picturefill/issues/713#issuecomment-520265132). I know this can't be made perfect without any additional hinting attribute but the proposed source selection tend to take much higher candidates on the low end (which would help here) and tend to take much lower candidates on the higher end (which would help especially with the new fancy smartphones).

**Comment by lucasw87** [comment]
@aFarkas 
I see, I understand your point about a necessity to optimize for other devices not just 1x and 2x, but I can't optimize for everything between them 1.1x, 1.2x, 1.3x, and so on, or there would be dozens of variations of the same image on the server that take space and everything looks messy.

Also, if I replace the 2x with a 1.4x candidate as you suggested, devices with 2x will suffer and everything will look blurry on Retina, so that's not an option.

I could indeed replace 1x with 1.2x images but then I will have to always serve 1.2x images even when there's no need for that. Moreover, creating new versions of images will take me dozens hours of work, cause' I do have a lot of images on my site (hundreds of them).

Describing 2x images as 1.4x seems like an optimal solution for me, though how do I actually do it? As I previously mention, I use the WP Retina 2x plugin where I selected the Picturefill method whose script I have no control over. So what do I do in this situation?

**Comment by lucasw87** [comment]
@aFarkas Any ideas on my situation? I'm looking forward to your reply. Your help is highly appreciated!

**Comment by aFarkas** [comment]
@lucasw87 
> Describing 2x images as 1.4x seems like an optimal solution for me, though how do I actually do it? As I previously mention, I use the WP Retina 2x plugin where I selected the Picturefill method whose script I have no control over. So what do I do in this situation?

I can't really tell you. The picturefill script here is only the so called polyfill. Which means that it is only executed in browsers which do not support this feature natively. 

What you have to change is your HTML.

So if you have the following markup:

```html
<img alt="PianoDreamers.com" width="500" height="133" srcset="/logo-pianodreamers.png, /logo-pianodreamers@2x.png 2x">
```

You should change it to:

```html
<img alt="PianoDreamers.com" width="500" height="133" srcset="/logo-pianodreamers.png, /logo-pianodreamers@2x.png 1.4x">
```

This is done by the wp plugin. I don't know this plugin so I can't tell how you would do it there. The best way would be to ask the plugin author to help you here.

**Comment by lucasw87** [comment]
@aFarkas Thanks a lot of the idea! It wasn't actually that hard, as I was able to do it myself. 

I simply went to the core.php file of the plugin and modified a few lines. Now, it's all nice and sharp in Chrome and Opera two, since my @2x are now considered @1.4x.

Thanks again for your help! You saved me a lot of time and struggle!
